from dataclasses import dataclass
from enum import Enum
from typing import Callable, Type, Any, Optional, List, Dict, Union, Literal
from uuid import UUID
from pydantic import BaseModel, Field

@dataclass
class LLMTool:
    name: str
    description: str
    args_schema: Type[BaseModel]
    func: Callable[..., Any]

class RoleType(str, Enum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"

class ToolCallFunction(BaseModel):
    name: str
    arguments: str  # JSON string

class ToolCall(BaseModel):
    id: str
    type: Literal["function"] = "function"
    function: ToolCallFunction

class LLMMessage(BaseModel):
    """Standard structure for a single chat message."""
    role: RoleType
    content: Optional[str] = None
    
    # When role="assistant", LLM might return tool calls
    tool_calls: Optional[List[ToolCall]] = None
    
    # When role="tool", we must provide tool_call_id and name
    tool_call_id: Optional[str] = None
    name: Optional[str] = None # Tool name

class ChatHistory(BaseModel):
    messages: List[LLMMessage]

class LLMPayload(BaseModel):
    """
    Final payload to send to the LLM.
    Generated by Level 2 build_llm_payload and passed to Level 4.
    """
    messages: List[LLMMessage]
    
    # List of Tool JSON Schemas
    tools: Optional[List[Dict[str, Any]]] = None
    
    # 'auto', 'none', or specific tool
    tool_choice: Optional[Union[str, Dict[str, Any]]] = "auto"

class UserQuery(LLMMessage):
    role: Literal[RoleType.USER] = RoleType.USER
    content: str

class SOPPreference(BaseModel):
    id: UUID
    user_id: UUID
    session_ids: List[UUID]
    subject: str
    content: str
    keywords: List[str]

class SessionContext(BaseModel):
    user_sop_preferences: List[SOPPreference]

