from dataclasses import dataclass
from enum import Enum
from typing import Callable, Type, Any, Optional, List, Dict, Union, Literal
from uuid import UUID
from pydantic import BaseModel, Field
from app.chat_service.core.config import settings

@dataclass
class LLMTool:
    name: str
    description: str
    args_schema: Type[BaseModel]
    func: Callable[..., Any]

class RoleType(str, Enum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"

class ToolCallFunction(BaseModel):
    name: str
    arguments: str  # JSON string
    vendor_extra: Optional[Dict[str, Any]] = None

class ToolCall(BaseModel):
    id: str
    type: Literal["function"] = "function"
    function: ToolCallFunction

class LLMMessage(BaseModel):
    """Standard structure for a single chat message."""
    role: RoleType
    content: Optional[str] = None
    
    # When role="assistant", LLM might return tool calls
    tool_calls: Optional[List[ToolCall]] = None
    
    # When role="tool", we must provide tool_call_id and name
    tool_call_id: Optional[str] = None
    name: Optional[str] = None # Tool name
    
    # Metadata
    model: Optional[str] = None
    tokens: Optional[int] = None

class ChatHistory(BaseModel):
    messages: List[LLMMessage]

class LLMPayload(BaseModel):
    """
    Final payload to send to the LLM.
    Generated by Level 2 build_llm_payload and passed to Level 4.
    """
    messages: List[LLMMessage]
    
    # List of Tool JSON Schemas
    tools: Optional[List[Dict[str, Any]]] = None
    
    # 'auto', 'none', or specific tool
    tool_choice: Optional[Union[str, Dict[str, Any]]] = "auto"

class UserQuery(LLMMessage):
    role: Literal[RoleType.USER] = RoleType.USER
    content: str

class SOPPreference(BaseModel):
    id: UUID
    user_id: UUID
    session_ids: List[UUID]
    subject: str
    content: str
    keywords: List[str]

class SessionContext(BaseModel):
    user_sop_preferences: List[SOPPreference]


# ==========================================
# Level 4: Stream Types & Configuration
# ==========================================

class StreamEventType(str, Enum):
    TEXT_CHUNK = "text_chunk"
    TOOL_CALL = "tool_call"
    STATS = "statistic"
    ERROR = "error"
    STATUS = "status"
    RUN_FINISH = "run_finish"

class BaseStreamReply(BaseModel):
    event_type: StreamEventType
    seq_id: int = Field(..., description="Sequence ID for ordering")

class MessageChunkEvent(BaseStreamReply):
    event_type: Literal[StreamEventType.TEXT_CHUNK] = StreamEventType.TEXT_CHUNK
    content: str

class ToolCallChunkEvent(BaseStreamReply):
    event_type: Literal[StreamEventType.TOOL_CALL] = StreamEventType.TOOL_CALL
    tool_name: Optional[str] = None
    args_chunk: str
    index: int = 0
    vendor_extra_chunk: Optional[Dict[str, Any]] = None

class StatisticEvent(BaseStreamReply):
    event_type: Literal[StreamEventType.STATS] = StreamEventType.STATS
    input_tokens: int
    output_tokens: int
    response_duration: float

class StatusEvent(BaseStreamReply):
    event_type: Literal[StreamEventType.STATUS] = StreamEventType.STATUS
    message: str
    tool_name: Optional[str] = None
    status: Literal["running", "success", "failed"] = "running"

class RunFinishEvent(BaseStreamReply):
    event_type: Literal[StreamEventType.RUN_FINISH] = StreamEventType.RUN_FINISH
    generated_messages: List[LLMMessage]

StreamReply = Union[
    MessageChunkEvent, 
    ToolCallChunkEvent, 
    StatisticEvent, 
    StatusEvent,
    RunFinishEvent
]

